Homepage is tested
necyberteam/cyberteam_drupal pull request #1006
Opened 2023-11-13 18:20 UTC by laheara143

## Describe context / purpose for this PR
This PR adds a test for the homepage of asp
## Issue link

## Any other related PRs?

## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

2023-11-13 19:28 UTC, jasperlieber requested changes

2023-11-13 19:28 UTC, jasperlieber commented on tests/cypress/cypress/support/commands.js
> +  cy.contains(text);
you should look for the text within the cta block -- something like `cy.get("#cta").contains(text) should do that

2023-11-13 19:28 UTC, jasperlieber commented on tests/cypress/cypress/support/commands.js
> +  cy.should("have.attr", "href", href);
same as above

2023-11-14 16:18 UTC, laheara143 commented
Tests are passing but two other separate tests from this PR are not

2023-11-15 20:45 UTC, closed without merging