Tetsing the term selector and tags page
necyberteam/cyberteam_drupal pull request #646
Opened 2023-05-27 15:27 UTC by laheara143

## Describe context / purpose for this PR
Adding in tests to verify the tags page shows announcements and events. Also testing the term selector on the events and announcements page.

## Issue link

https://cyberteamportal.atlassian.net/browse/D8-1329

## Any other related PRs?

## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

2023-05-27 18:31 UTC, laheara143 commented
Andrew Pasquale 
3 days ago

Events tests:

Create 2 upcoming events with known values and a specific tag. Test the relevant tags page (e.g. /tags/data-analysis) to make sure those 2 events are there.

Add a 3rd event with the same tag. Test the page again and make sure the “See all Events with this tag” button is there. 

Test the all events with this tag page to for the 3rd event

Announcements tests:

(Note ACCESS News is now Announcements)

Create 2 announcements with a given tag. Test the relevant tag page to make sure those 2 announcements are there. Add a 3rd announcement and make sure the “See all announcements with this tag” button is there.

Test the all announcements with this tag page for the 3rd announcement.

Pick a tag with 3 or more announcements, test for

2023-06-14 19:33 UTC, a-pasquale commented
@laheara143 What's the status of this pull request?

2023-06-14 22:40 UTC, laheara143 commented
@a-pasquale Working on this now I had some code space issues but I just resolved them. Should be done soon

2023-06-15 00:23 UTC, laheara143 commented
@a-pasquale This pr seems to be all set now!

2023-07-25 19:20 UTC, jasperlieber requested changes

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/asp/cssn_form_request.feature
> +    #Then I should see "mentor"
is there a jira ticket for this?

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/templates/tags-individual.feature
> +    #Then I should see "test project description"
either remove comment or fix the test?

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/asp/events-tags.feature
> +    # TODO: be able to save an event with a date and time
is there a jira ticket for this?

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/asp/events-tags.feature
> +    #When I fill in "Create Events Between" with "01/23/2052"
remove comments, or fix test?  or add jira ticket to fix the test?

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/asp/announcement-tags.feature
> +    #When I fill in "Body" with "Test3"
remove comments, or fix test?  or add jira ticket to fix the test?

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/asp/announcement-tags.feature
> +    #When I fill in "Body" with "Test4"
remove comments, or fix test?  or add jira ticket to fix the test?

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/asp/announcement-tags.feature
> +    #When I fill in "Body" with "Test"
remove comments, or fix test?  or add jira ticket to fix the test?

2023-07-25 19:20 UTC, jasperlieber commented on tests/behat/features/asp/announcement-tags.feature
> +    #When I fill in "Body" with "Test2"
remove comments, or fix test?  or add jira ticket to fix the test?

2023-07-26 15:20 UTC, jasperlieber commented
redoing this work on a new fresh branch "redo--D8-1329|TagsPage"

2023-07-26 15:20 UTC, closed without merging