projects-individual.feature section needed to be fixed
necyberteam/cyberteam_drupal pull request #691
Opened 2023-06-28 16:39 UTC by alvaradom0321

## Describe context / purpose for this PR
projects-individual.feature section needs to be fixed

## Issue link
https://cyberteamportal.atlassian.net/browse/D8-1628

## Any other related PRs?
N/A

## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

2023-06-29 15:44 UTC, laheara143 commented on tests/behat/features/templates/projects-individual.feature
> +    #Then I should see "Login to Add New Project"
Does this section not work?

2023-07-03 16:04 UTC, alvaradom0321 commented on tests/behat/features/nect/1-nect-domaindefault.feature
> +    #Then I should see "Institutions in Northern New England"
I tried it did not pass

2023-07-03 16:06 UTC, alvaradom0321 commented on tests/behat/features/templates/projects-individual.feature
> +    #Then I should see "Login to Add New Project"
I do not remember

2023-07-25 19:59 UTC, jasperlieber requested changes
Need Jira ticket numbers by any #TODO lines

2023-07-29 01:13 UTC, closed without merging

2023-07-29 01:13 UTC, jasperlieber commented
redone on https://github.com/necyberteam/cyberteam_drupal/pull/756