Fixing section of Projects Test
necyberteam/cyberteam_drupal pull request #716
Opened 2023-07-07 17:35 UTC by laheara143

## Describe context / purpose for this PR
Projects test has certain sections that need fixing
## Issue link
https://cyberteamportal.atlassian.net/browse/D8-1626
## Any other related PRs?

## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

2023-07-13 14:33 UTC, laheara143 commented
The mentor must have the role “mentor” or “researcher/educator”. The student must have the “student-facilitator” role. The autocomplete does not fiilter by roles, but people without these roles are rejected.

2023-07-15 14:44 UTC, laheara143 commented
Issue w/ page not loading, other test pass

2023-07-25 18:59 UTC, jasperlieber requested changes

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/asp/cssn_form_request.feature
> +    #Then I should see "Thanks for updating your CSSN membership."
Either remove the comments, or tag them with TODO and include jira ticket

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/asp/join-cssn-auth.feature
> +    #Then I should see "Thanks for updating your CSSN membership."
Either remove the comments, or tag them with TODO and include jira ticket

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/asp/match-plus-unauth.feature
> +    #Then I should see "University of North Dakota"
Would adding a wait help?  Either remove the comments, or tag them with TODO and include jira ticket

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/asp/match-plus-unauth.feature
> +    #Then I should see "GPU-accelerated ice sheet flow modeling"
Either remove the comments, or tag them with TODO and include jira ticket

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/asp/match-plus-unauth.feature
> +    #Then I should see "Recruiting"
i think this is now "Reviewing" but need to double check

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/asp/ondemand-unauth.feature
> +    #When I go to "/ondemand"
Either remove the comments, or tag them with TODO and include jira ticket

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/templates/projects-individual.feature
> +@asp
needs to be templates

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/templates/projects-individual.feature
> +    #When I fill in "edit-mentee-s-items-0-item-" with "Test Smith (TestSmith)"
Either remove the comments, or tag them with TODO and include jira ticket

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/templates/projects-individual.feature
> +    When I select "Delete submission" from "edit-action"
Either remove the comments, or tag them with TODO and include jira ticket

2023-07-25 18:59 UTC, jasperlieber commented on tests/behat/features/templates/projects-individual.feature
>      #When I click " interested"
Either remove the comments, or tag them with TODO and include jira ticket

2023-08-01 20:31 UTC, jasperlieber commented
redoing this with https://github.com/necyberteam/cyberteam_drupal/pull/761

2023-08-01 20:31 UTC, closed without merging