Adding in Cypress testing for new ACCESS theme
necyberteam/cyberteam_drupal pull request #965
Opened 2023-10-17 18:34 UTC by laheara143

## Describe context / purpose for this PR
Adding in cypress tests for Asp new theme:
XDMoD
CCEP
CI Link
CI LInks
and more
## Issue link
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/boards/6?sprints=72
## Any other related PRs?

## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

2023-10-17 19:11 UTC, a-pasquale commented on tests/cypress/cypress/e2e/accessmatch/pegasus.cy.js
> +    cy.contains("Why use workflows").click();
Is this an accordion? There should be comments here describing what the test is testing for.

2023-10-17 19:11 UTC, a-pasquale commented on tests/cypress/cypress/e2e/accessmatch/pegasus.cy.js
> +    and Verifying links and images load in,
We're not verify this here. Please remove the description.

2023-10-17 19:12 UTC, a-pasquale commented on tests/cypress/cypress/e2e/accessmatch/science-gateways.cy.js
> +    and Verifying links and images load in,
Remove this since we're not verifying that.

2023-10-17 19:12 UTC, a-pasquale commented on tests/cypress/cypress/e2e/accessmatch/science-gateways.cy.js
> +    cy.contains("How do I use a Gateway?").click();
Comment that this is testing an accordion please

2023-10-17 19:14 UTC, a-pasquale commented
The naming of ci-links and ci-link is backwards. The listing page should be named ci-links and the individual CI Link page should be ci-link.

When you're ready to merge, please convert from a draft.

2023-10-24 19:20 UTC, laheara143 commented
Changing Affinity Test to Individual Test

2023-11-01 17:57 UTC, jasperlieber requested changes

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/add-interests.cy.js
> +      ":nth-child(1) > :nth-child(2) > :nth-child(1) > .view-display-id-page_2 > .view-content > .add-interest-list > ul > :nth-child(1) > :nth-child(1) > span > .d-inline-flex > .d-none > .flag > .u
hmm, not sure what is being clicked here

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/add-interests.cy.js
> +  });
add interests is now under community persona, so this code looks pretty old.  i think a good test of adding interests is:

- on cp/add-interests as an auth user, click a few interests
- verify those ui element are changed (like 'selected' or whatever the change is)
- on the users persona page, verify they now have those interests
- back on add-interest, unselect those interests
- verify the ui changes
- on the cp page, verify they don't have those interests

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/add-skills.cy.js
> +});
see comments for add-interests -- do similar here?

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/affinity-groups-indie.cy.js
> +});
i've written some good Ag tests.  i think we can delete this.

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/announcment-form.cy.js
> +
filename for this is misspelled

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/announcments-page.cy.js
> +*/
filename misspelled

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/announcments-page.cy.js
> +    //Testing created annoucement
announcement

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/announcments-page.cy.js
> +    cy.contains("login");
better to verify text with something like this:
```
  cy.get('.field--name-field-tags')
      .contains('ACCESS-website')
      .should('have.attr', 'href', '/tags/access-website');
```

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/ccep-details.cy.js
> +*/
would be good to verify the Apply to CCEP button with something like
```

    cy.get('.affinity-group-buttons')
      .contains('Q&A')
      .should('have.attr', 'href')
      .and('contain', 'https://ask.cyberinfrastructure.org/c/access-forums/access-support/73');
```

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/ci-link-auth.cy.js
> +  });
check something after flagging?

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/ci-link-auth.cy.js
> +    cy.contains("0");
just looking or "0" or "1" is too general, right?  can look for 0 or 1 but needs to be inside a DOM element

2023-11-01 17:57 UTC, jasperlieber commented on tests/cypress/cypress/e2e/accessmatch/ci-link-auth.cy.js
> +    cy.contains("0");
this test is for an invididual ci-link, right?  rename the test to include "individual"?  

is there more about an ci-link that should be tested?

2023-11-01 20:00 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/ci-link-indie-auth.cy.js
> +    //Vote feature  When Vote button is clicked the user is brought to an access denied page. Section is disabled until this is figured out
When vote was clicked it brought me to a Access denied page

2023-11-01 20:01 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/ccep-details.cy.js
> +    //Verifying Join CCEP Button  Test fails disabling for now
Not sure why but even though there is a button it fails when the below lines are ran

2023-11-02 18:00 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/ccep-details.cy.js
> +    //Verifying Join CCEP Button  Test fails disabling for now
Was able to fix!

2023-11-06 19:59 UTC, laheara143 commented
Announcements and Events forms are failing upon submission and due to this the event and announcement test fail as well.
![image](https://github.com/necyberteam/cyberteam_drupal/assets/77558582/25c6bab1-e100-48f7-912b-fa0fa2a29857)

2023-11-10 23:01 UTC, a-pasquale commented on tests/cypress/cypress/e2e/accessmatch/tools/xdmod.cy.js
> +    cy.visit("/xdmod");
/tools/xdmod

2023-11-14 23:55 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/announcements/announcements-page.cy.js
> +    cy.contains("http://example-0.com").click();
I do not see the login tag in the row of the announcement. I tried checking on the md website to see if it shows there but it seems to be down 
![image](https://github.com/necyberteam/cyberteam_drupal/assets/77558582/b982d4f0-918a-45f2-ad3f-828ef7ebbd77)

2023-11-14 23:59 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/announcements/events-add.cy.js
> +    cy.loginAs("administrator@amptesting.com", "b8QW]X9h7#5n");
I can change it to an auth user but then the event will not be published. Should a separate auth test be made so that can be covered as well?

2023-11-15 00:00 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/announcements/events-add.cy.js
> +    cy.loginAs("administrator@amptesting.com", "b8QW]X9h7#5n");
Nevermind I see the answer below

2023-11-15 18:14 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/knowledge-base/ci-links/ci-link-indie-auth.cy.js
> +        cy.get(".flag > .flex").click();
Seems like it could be the one above or this cy.get('.flag > .flex > .me-2')

2023-11-15 18:22 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/knowledge-base/ci-links/ci-link-indie-auth.cy.js
> +        cy.get(".ps-5").contains("Flag this CI Link").click();
I can have it click the text "Flag this CI Link"

2023-11-15 18:32 UTC, laheara143 commented on tests/cypress/cypress/e2e/accessmatch/tools/ondemand.cy.js
> +    cy.get('[style=""] > .bg-white').contains(
Cypress element selector shows this as an option as well. cy.get('[open=""] > .bg-white')

2023-11-15 21:00 UTC, closed without merging

2023-11-15 21:01 UTC, laheara143 commented
Closed and remade on #1013